#!/usr/bin/env bash
#10-fizzbuzz
i=1
while [ $i -eq 100 ]
do
if [ "$i%3" == "0" ]
then
echo "Fizz"
elif [ "$i%5" == "0" ]
then
echo "Buzz"
elif [ "$i%3" == "0" -a "$i%5" == "0" ]
then
echo "FizzBuzz"
else
echo "$i"
fi
((i++))
done
