#!/usr/bin/env bash
#9-to_file_or_not_to_file
item = "school"
if [ -e "$item"]
then
echo "School file exists"
if [ -z "$item" ]
then
echo "school file is empty"
else
echo "school file is not empty"
fi
if [ -f $item]
then
echo "school is a regular file"
else
continue
fi
else
echo "School file doesnot exist"
fi
